### PR TITLE
add cmake support

### PR DESCRIPTION
**Pull request by fyu**

### CODE REVIEW

**Comment by danielsuo** [comment]
This might fail on OS X, which has cuda in lib instead of lib64.

**Comment by fyu** [comment]
@danielsuo Can you test it on Mac? I think it will work. I do want to clean up the file in a following commit.

**Comment by danielsuo** [comment]
Resolved both the lib vs lib64 issue and the pthread problem. It turns out
that TRY_COMPILE on OS X doesn't want to work for pthread.h because we need
to enable both C and CXX in the project command.

**Comment by danielsuo** [comment]
Both 2cf9229 and c7b834c cause the error pasted below on Ubuntu 15.04 for me. Fixed with 6f9f4f0.

```
/usr/bin/ld: CMakeFiles/marvin.dir/marvin_generated_marvin.cu.o: undefined reference to symbol 'pthread_create@@GLIBC_2.2.5'
/lib/x86_64-linux-gnu/libpthread.so.0: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
CMakeFiles/marvin.dir/build.make:375: recipe for target 'marvin' failed
make[2]: *** [marvin] Error 1
CMakeFiles/Makefile2:60: recipe for target 'CMakeFiles/marvin.dir/all' failed
make[1]: *** [CMakeFiles/marvin.dir/all] Error 2
Makefile:75: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by fyu** [comment]
Resolved by commit @947c456d80e4710d130b13ac4314029f3cf48259

**Pull request closed without merging**
